name: Release Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true
        type: string

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Export Game
        uses: firebelley/godot-export@v5.2.1
        with:
            godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2/mono/Godot_v4.2-stable_mono_linux_x86_64.zip
            godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2/mono/Godot_v4.2-stable_mono_export_templates.tpz
            relative_project_path: ./
            cache: true
            archive_output: true
            export_debug: false
      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with: 
          allowUpdates: true
          artifacts: "/home/runner/.local/share/godot/archives/*"
          tag: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          generateReleaseNotes: true
